#!/bin/sh
get_hostname=$(cat ./etc/hostname)
get_admin=$(cat ./etc/admin)
get_shellprompt=$(cat ./etc/shellprompt)
cat ./etc/welcome # Like /etc/motd in *NIX
while [ true ]; do
    read -p "$get_hostname:[$get_admin]$get_shellprompt " cmd
    ./bin/$cmd
done
