#!/bin/bash
export OSNAME="WhiteDevilOS"
export KERNEL_NAME="WhiteDevilKernel"
export KERNEL_VER="WDKv1"
export PRETTY_NAME="WhiteDevil-OS"
export HOME_PAGE="github.com/diabloblanko/whitedevil-os"
export ISSUES="github.com/diabloblanko/whitedevil-os/issues"
export PYV=$(python --version)